global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'ingestion-service'
    static_configs:
      - targets: ['ingestion-service:3000']

  - job_name: 'ml-inference-service'
    static_configs:
      - targets: ['ml-inference-service:8000']
